name: Publish

on:
  push:
    branches: [ master ]

    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Run yarn install
      run: yarn install

    - name: Run yarn test
      run: yarn test
    
    - name: Run ttsc build
      run: |
        rm -rf dist
        yarn run ttsc
    
    - name: Run git commit
      run: |
        git add dist -f
        git commit -m 'ci(dist): automatic new publish'
        git push origin master